// Firebase push notification methods are not automated.
//
// Methods:
//   POST /api/2.0/settings/push/docregisterdevice  (docRegisterPusnNotificationDevice)
//   PUT  /api/2.0/settings/push/docsubscribe        (subscribeDocumentsPushNotification)
//
// Reason: both endpoints require a real Firebase device token generated by the
// Firebase client SDK on an actual device or browser. Without a Firebase project
// and its credentials integrated into the test environment, it is not possible
// to obtain a valid token. Passing a random string would only verify that the
// server stores arbitrary data, not that push notifications work end-to-end.
// This belongs to e2e / mobile testing scope, not the API test suite.
