// GET /oauth2/authorize (authorizeOAuth) cannot be tested automatically:
// the flow requires a registered OAuth client (valid client_id) and browser interaction
// (user consent screen). The endpoint responds with an HTTP redirect (302), not JSON.

// POST /oauth2/token (exchangeToken) cannot be tested automatically:
// requires a valid one-time authorization code produced by the authorizeOAuth browser flow.
// Without a live code the server rejects the request immediately.

// POST /oauth2/authorize (submitConsent) cannot be tested automatically:
// processes the user consent form submitted from the browser (Deny/Allow screen).
// requires a valid session state token generated by the authorizeOAuth browser flow.
