import dotenv from "dotenv";
import process from "node:process";

dotenv.config();

interface Config {
  PORTAL_REGISTRATION_URL: string;
  DOCSPACE_OWNER_EMAIL: string;
  DOCSPACE_OWNER_PASSWORD: string;
  MACHINEKEY: string;
  PKEY: string;
  LOCAL_PORTAL_DOMAIN: string;
  NEXTCLOUD_URL: string;
  NEXTCLOUD_LOGIN: string;
  NEXTCLOUD_PASSWORD: string;
  S3_ACCESS_KEY: string;
  S3_SECRET_KEY: string;
  S3_BUCKET: string;
  S3_REGION: string;
  DEEPSEEK_API_KEY: string;
  XAI_API_KEY: string;
  GOOGLE_AI_API_KEY: string;
  OPENROUTER_API_KEY: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  TOGETHER_AI_API_KEY: string;
  EXA_API_KEY: string;
  GITHUB_MCP_ENDPOINT: string;
}

const config: Config = {
  PORTAL_REGISTRATION_URL:
    process.env.PORTAL_REGISTRATION_URL ??
    "https://onlyoffice.io/apisystem/portal",
  DOCSPACE_OWNER_EMAIL:
    process.env.DOCSPACE_OWNER_EMAIL ?? "integration-test-email@gmail.com",
  DOCSPACE_OWNER_PASSWORD: process.env.DOCSPACE_OWNER_PASSWORD ?? "test1234",
  MACHINEKEY: process.env.MACHINEKEY ?? "",
  PKEY: process.env.PKEY ?? "",
  LOCAL_PORTAL_DOMAIN: process.env.LOCAL_PORTAL_DOMAIN ?? "",
  NEXTCLOUD_URL: process.env.NEXTCLOUD_URL ?? "NEXTCLOUD_URL_NOT_CONFIGURED",
  NEXTCLOUD_LOGIN:
    process.env.NEXTCLOUD_LOGIN ?? "NEXTCLOUD_LOGIN_NOT_CONFIGURED",
  NEXTCLOUD_PASSWORD:
    process.env.NEXTCLOUD_PASSWORD ?? "NEXTCLOUD_PASSWORD_NOT_CONFIGURED",
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY ?? "S3_ACCESS_KEY_NOT_CONFIGURED",
  S3_SECRET_KEY: process.env.S3_SECRET_KEY ?? "S3_SECRET_KEY_NOT_CONFIGURED",
  S3_BUCKET: process.env.S3_BUCKET ?? "S3_BUCKET_NOT_CONFIGURED",
  S3_REGION: process.env.S3_REGION ?? "S3_REGION_NOT_CONFIGURED",
  DEEPSEEK_API_KEY:
    process.env.DEEPSEEK_API_KEY ?? "DEEPSEEK_API_KEY_NOT_CONFIGURED",
  XAI_API_KEY: process.env.XAI_API_KEY ?? "XAI_API_KEY_NOT_CONFIGURED",
  GOOGLE_AI_API_KEY:
    process.env.GOOGLE_AI_API_KEY ?? "GOOGLE_AI_API_KEY_NOT_CONFIGURED",
  OPENROUTER_API_KEY:
    process.env.OPENROUTER_API_KEY ?? "OPENROUTER_API_KEY_NOT_CONFIGURED",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? "OPENAI_API_KEY_NOT_CONFIGURED",
  ANTHROPIC_API_KEY:
    process.env.ANTHROPIC_API_KEY ?? "ANTHROPIC_API_KEY_NOT_CONFIGURED",
  TOGETHER_AI_API_KEY:
    process.env.TOGETHER_AI_API_KEY ?? "TOGETHER_AI_API_KEY_NOT_CONFIGURED",
  EXA_API_KEY: process.env.EXA_API_KEY ?? "EXA_API_KEY_NOT_CONFIGURED",
  GITHUB_MCP_ENDPOINT:
    process.env.GITHUB_MCP_ENDPOINT ?? "GITHUB_MCP_ENDPOINT_NOT_CONFIGURED",
};

export default config;
